//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tek_Fakultesi.Models.Entity_Fremawork
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANISMAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DANISMAN()
        {
            this.DANISMAN_GOREVLENDİRME = new HashSet<DANISMAN_GOREVLENDİRME>();
            this.OGR_DANISMAN = new HashSet<OGR_DANISMAN>();
        }
    
        public int ID { get; set; }
        public string KUL_AD { get; set; }
        public string UNVAN { get; set; }
        public string AD { get; set; }
        public string SOYAD { get; set; }
        public Nullable<int> BIRIMID { get; set; }
        public string SİFRE { get; set; }
        public Nullable<int> ROLID { get; set; }
        public string image { get; set; }
        public Nullable<bool> cinsiyet { get; set; }
    
        public virtual BIRIMLER BIRIMLER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANISMAN_GOREVLENDİRME> DANISMAN_GOREVLENDİRME { get; set; }
        public virtual ROL ROL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OGR_DANISMAN> OGR_DANISMAN { get; set; }
    }
}
