//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tek_Fakultesi.Models.Entity_Fremawork
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANISMAN_GOREVLENDİRME
    {
        public int GOREV_ID { get; set; }
        public int GOREVLENDİREN_DANISMAN { get; set; }
        public string GOREVLENEN_OGR_ID { get; set; }
        public Nullable<System.DateTime> GOREV_GİRİST { get; set; }
        public Nullable<System.DateTime> GOREV_SONLANDIRMAT { get; set; }
        public string GOREV_ACIKLAMA { get; set; }
    
        public virtual DANISMAN DANISMAN { get; set; }
    }
}
