//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tek_Fakultesi.Models.Entity_Fremawork
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MENU()
        {
            this.MENUROL = new HashSet<MENUROL>();
            this.MENUROL1 = new HashSet<MENUROL>();
        }
    
        public int ID { get; set; }
        public string MENU_ADI { get; set; }
        public Nullable<int> USTMENU { get; set; }
        public Nullable<int> GORUNURLUK { get; set; }
        public string CONTOLLERNAME { get; set; }
        public string ACTIONNAME { get; set; }
        public string ICON { get; set; }
        public Nullable<int> SIRANO { get; set; }
        public string ACIKLAMA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MENUROL> MENUROL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MENUROL> MENUROL1 { get; set; }
    }
}
