//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tek_Fakultesi.Models.Entity_Fremawork
{
    using System;
    using System.Collections.Generic;
    
    public partial class OGR_DANISMAN
    {
        public int ID { get; set; }
        public Nullable<int> OGR_ID { get; set; }
        public Nullable<int> DANISMAN_ID { get; set; }
    
        public virtual DANISMAN DANISMAN { get; set; }
        public virtual OGRENCİ OGRENCİ { get; set; }
    }
}
