//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tek_Fakultesi.Models.Entity_Fremawork
{
    using System;
    using System.Collections.Generic;
    
    public partial class OGRENCİ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OGRENCİ()
        {
            this.OGR_DANISMAN = new HashSet<OGR_DANISMAN>();
        }
    
        public int ID { get; set; }
        public string KUL_AD { get; set; }
        public string SİFRE { get; set; }
        public string OGR_AD { get; set; }
        public string OGR_SOYAD { get; set; }
        public Nullable<int> OGR_BOLUM { get; set; }
        public string OGR_SINIF { get; set; }
        public string OGR_ORT { get; set; }
        public string image { get; set; }
        public bool Cinsiyet { get; set; }
        public string D_Yeri { get; set; }
        public Nullable<System.DateTime> D_Tarihi { get; set; }
        public string Konya_Adresi { get; set; }
        public string Cep { get; set; }
        public string E_posta { get; set; }
        public Nullable<double> Fakulte_girisp { get; set; }
        public string İkametgah_Adresi { get; set; }
        public string A_AdSoyad { get; set; }
        public string A_OgrenimDurumu { get; set; }
        public Nullable<bool> A_Saglık_durumu { get; set; }
        public string B_AdSoyad { get; set; }
        public string B_OgrenimDurumu { get; set; }
        public Nullable<bool> B_Saglık_durumu { get; set; }
        public Nullable<int> Aile_Birey_Sayisi { get; set; }
        public string Gecim_Sorumluluk_Sahibi { get; set; }
        public Nullable<int> Kardes_Sayisi { get; set; }
        public string Kan_Grubu { get; set; }
        public string Hastaliklar { get; set; }
        public Nullable<int> Ev_Sayisi { get; set; }
        public Nullable<int> Araba_Sayisi { get; set; }
        public string Sosyal_Guvence { get; set; }
        public string SG_Kim { get; set; }
        public Nullable<double> Toplam_Gelir { get; set; }
        public Nullable<int> Kredi_Burs { get; set; }
        public string Yakin_Adsoyad { get; set; }
        public string Yakinlik_derece { get; set; }
        public string Yakin_Tel { get; set; }
        public string Özel_Durum { get; set; }
        public Nullable<int> OGR_DAN { get; set; }
    
        public virtual BIRIMLER BIRIMLER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OGR_DANISMAN> OGR_DANISMAN { get; set; }
    }
}
